---
title: "Estimation growth parameters and natural mortality rates for wedge clam (*Donax trunculus*) regarding conservation figures in Cádiz GUlf, Spain"
subtitle: ""
author:
  - Mardones Mauricio^[Instituto Español de Oceanografía, mauricio.mardones@ieo.csic.es]
  - Marina Delgado^[Instituto Español de Oceanografía, marina.delgado@ieo.csic.es]
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::pdf_document2:
    number_sections: false
fig_caption: yes
bibliography: Param_donax.bib
csl: apa.csl
link-citations: yes
toc: false
linkcolor: blue
linestretch: 1.3
header-includes:
- \fontsize{12}{16}
- \selectfont
- \usepackage{lscape}
---
\newpage
\tableofcontents
\newpage


```{r setup1, echo=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      fig.align = 'center',
                      fig.pos = "H",
                      dev = 'jpeg',
                      dpi = 300)
#XQuartz is a mess, put this in your onload to default to cairo instead
options(bitmapType = "cairo") 
# (https://github.com/tidyverse/ggplot2/issues/2655)
# Lo mapas se hacen mas rapido
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggridges)
library(readxl)
library(here)
library(lubridate)
library(readr)
library(ggthemes)
library(hrbrthemes)
library(kableExtra)
library(gtsummary)
```

# ABSTRACT

# INTRODUCTION



